Added jekyll assets, updated references and added service worker
pythonindia/inpycon2020 pull request #44
Opened 2020-07-13 14:00 UTC by bhansa

Hi, 

I have added a service worker to root directory of this project, I have followed this [blog post](https://alxgbsn.co.uk/2017/12/08/adding-a-service-worker-to-jekyll/) for steps to add a service worker to a jekyll site using [jekyll-assets](https://github.com/envygeeks/jekyll-assets). For our assets and code to work with jekyll assets, I have made below few changes:
  - Updated dependencies, added jekyll-assets
  - Update *assets* folder to *_assets* to create an asset pipeline.
  - Update references in our html files as well as data yaml files, used `{% asset asset_name ...attributes %}` syntax instead, more details can be found in the jekyll assets github page.

**Why jekyll asset**?
Since we want to update the cache version, as well as version the of resources/assets like css, js and images. Refer serviceWorker.js file for details.

Let me know if these changes are good, provide suggestions as well.

Thanks,
Bharat

Fixes #28

2020-07-16 18:27 UTC, ananyo2012 commented
@bhansa Thanks for your PR. This will add a lot of value to the website. I can't see the Netlify preview. Probably some issue with the asset links. Can you check what's the issue ?

2020-07-17 16:52 UTC, palnabarun commented on serviceWorker.js
> +{% endraw %}
nit: new line, please.

2020-07-17 16:55 UTC, palnabarun requested changes

2020-07-17 16:55 UTC, palnabarun commented on serviceWorker.js
> +    // }
nit: please remove the commented if not required.

2020-07-17 16:55 UTC, palnabarun commented on Gemfile
> +gem 'sprockets', '~> 3.7'
nit: new line, please.

2020-09-08 15:26 UTC, palnabarun commented
Changed base branch to `main` from `master`.

2020-09-10 12:25 UTC, SaptakS commented
@bhansa can you take a look at the merge conflicts?

2020-09-28 13:22 UTC, bhansa commented
Hi, I tried couple of times to resolve the issue with netlify build and jekyll assets and did not get any success with any of them and I could not spend much time to fix this PR.
I apologize for long delay and I think this PR will not add much value at this point of time, and I should focus on other open issues.
Hence, I am closing this PR.

2020-09-28 13:22 UTC, closed without merging